import { cn } from "@/lib/utils";
import "./globals.css";
import { Karla, Prompt } from "next/font/google";

const karla = Karla({
  subsets: ["latin-ext"],
  variable: "--font-karla",
});
const prompt = Prompt({
  subsets: ["latin-ext"],
  variable: "--font-prompt",
  weight: ["900"],
});

export const metadata = {
  title: "Dizajer Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          karla.variable,
          prompt.variable,
          "font-sans text-foreground bg-background"
        )}
      >
        {children}
      </body>
    </html>
  );
}
